baseURL = 'https://helloimhana123.github.io/hanaweb/'
locale = 'en-us'
title = "Hana's test"
theme = 'ananke-2.19.0'
Author = 'Pepe'
enableRobotsTXT = true
publishDir = "docs"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30
